services:
  - type: web
    name: WarBot
    envVars:
      - key: ABUSE
        value: False
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ENV
        sync: false
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
        sync: false
    buildCommand: pip3 install -r -U requirements.txt
    startCommand: python3 server.py & bash warbot
